#!/usr/bin/env python3
"""
CIQUAL → food_catalog seed generator.

Source: Table Ciqual (ANSES), https://ciqual.anses.fr/
Output: SQL file with INSERT ... ON CONFLICT DO UPDATE statements.

Runs with a Python venv having: pandas, xlrd, openpyxl.

Usage:
    python generate_seed.py <ciqual.xls> <output.sql> [<source_version>]

Example:
    python generate_seed.py ciqual_2020_07.xls ../../supabase/migrations/20260428100100_seed_ciqual.sql ciqual_2020_07

Calorie recovery:
    1. Primary column "Energie, Règlement UE N° 1169/2011 (kcal/100 g)".
    2. If missing, compute via Atwater: kcal = 4*protein + 9*fat + 4*carbs.
    3. Else 0 (likely water, salt, vinegar — genuinely calorie-free).

Values like "< 0.1" are treated as the half-threshold (0.05),
"traces"/"tr" as 0, "-"/empty as None.
"""

import sys
import re
import unicodedata
from pathlib import Path

import pandas as pd


COL_ID = "alim_code"
COL_NAME = "alim_nom_fr"
COL_KCAL_PRIMARY = "Energie, Règlement UE N° 1169/2011 (kcal/100 g)"
COL_PROTEIN = "Protéines, N x facteur de Jones (g/100 g)"
COL_FAT = "Lipides (g/100 g)"
COL_CARBS = "Glucides (g/100 g)"

SOURCE = "ciqual"


def parse_number(value, nullable: bool = True):
    """Return float or None. Handles French locale, '< X', 'traces', '-', empty."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        if pd.isna(value):
            return None
        return float(value)
    s = str(value).strip().replace(",", ".")
    if s in ("", "-", "nan", "NaN"):
        return None
    if s.lower() in ("traces", "tr"):
        return 0.0
    m = re.match(r"^<\s*([\d.]+)$", s)
    if m:
        return float(m.group(1)) / 2.0
    try:
        return float(s)
    except ValueError:
        return None


def normalize(name: str) -> str:
    """Lowercase, strip accents, collapse whitespace."""
    s = name.lower().strip()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"\s+", " ", s)
    return s


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def sql_value(v):
    if v is None:
        return "NULL"
    if isinstance(v, str):
        return f"'{sql_escape(v)}'"
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <ciqual.xls> <output.sql> [<source_version>]")
        sys.exit(1)

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    source_version = sys.argv[3] if len(sys.argv) >= 4 else "ciqual_2020_07"

    df = pd.read_excel(src, sheet_name="compo")
    before = len(df)
    df = df.drop_duplicates(subset=[COL_ID], keep="first")
    if len(df) != before:
        print(f"Dropped {before - len(df)} duplicate alim_code rows from {src.name}")
    print(f"Loaded {len(df)} rows from {src.name}")

    rows = []
    skipped = 0
    n_atwater = 0
    n_zero_kcal = 0

    for _, r in df.iterrows():
        try:
            food_id = int(r[COL_ID])
        except (ValueError, TypeError):
            skipped += 1
            continue

        raw_name = r[COL_NAME]
        name = str(raw_name).strip() if raw_name is not None and not pd.isna(raw_name) else ""
        if not name or name == "nan":
            skipped += 1
            continue

        protein = parse_number(r[COL_PROTEIN]) or 0.0
        fat = parse_number(r[COL_FAT])
        carbs = parse_number(r[COL_CARBS])

        kcal = parse_number(r[COL_KCAL_PRIMARY])
        if kcal is None or kcal == 0.0:
            # Atwater fallback (4P + 9F + 4C) when at least one macro is known
            macros_sum = protein + (fat or 0.0) + (carbs or 0.0)
            if macros_sum > 0:
                kcal = round(4 * protein + 9 * (fat or 0.0) + 4 * (carbs or 0.0), 1)
                n_atwater += 1
            else:
                kcal = 0.0
                n_zero_kcal += 1

        rows.append((
            food_id,
            name,
            normalize(name),
            protein,
            kcal,
            fat,
            carbs,
        ))

    print(f"Valid rows: {len(rows)} (skipped: {skipped})")
    print(f"  kcal recovered via Atwater: {n_atwater}")
    print(f"  kcal left at 0 (likely water/salt/vinegar): {n_zero_kcal}")

    with dst.open("w", encoding="utf-8") as f:
        f.write("-- ================================================================\n")
        f.write(f"-- {source_version} seed for food_catalog\n")
        f.write("-- Source: ANSES, Table Ciqual (https://ciqual.anses.fr/)\n")
        f.write("-- Generated by scripts/ciqual-seed/generate_seed.py\n")
        f.write("-- Calorie recovery: primary kcal column, Atwater fallback (4P+9F+4C).\n")
        f.write("-- ================================================================\n\n")

        f.write("BEGIN;\n\n")

        batch_size = 500
        for i in range(0, len(rows), batch_size):
            batch = rows[i:i + batch_size]
            f.write(
                "INSERT INTO food_catalog "
                "(id, ext_id, name, name_normalized, protein, calories, fat, carbs, "
                "default_portion_grams, source, source_version) VALUES\n"
            )
            values = []
            for (food_id, name, normalized, protein, calories, fat, carbs) in batch:
                values.append(
                    f"  ({food_id}, '{food_id}', "
                    f"{sql_value(name)}, "
                    f"{sql_value(normalized)}, "
                    f"{protein}, "
                    f"{calories}, "
                    f"{sql_value(fat)}, "
                    f"{sql_value(carbs)}, "
                    f"100, "
                    f"{sql_value(SOURCE)}, "
                    f"{sql_value(source_version)})"
                )
            f.write(",\n".join(values))
            f.write("\nON CONFLICT (source, ext_id) DO UPDATE SET\n")
            f.write("  name = EXCLUDED.name,\n")
            f.write("  name_normalized = EXCLUDED.name_normalized,\n")
            f.write("  protein = EXCLUDED.protein,\n")
            f.write("  calories = EXCLUDED.calories,\n")
            f.write("  fat = EXCLUDED.fat,\n")
            f.write("  carbs = EXCLUDED.carbs,\n")
            f.write("  source_version = EXCLUDED.source_version;\n\n")

        f.write("COMMIT;\n")

    print(f"Wrote {dst} ({dst.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
